name: Terraform Deploy

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.10.0"

      - name: Terraform Init
        run: |
          cd deployment 
          terraform init

      - name: Terraform Plan
        run: |
          cd deployment  
          terraform plan
      - name: Terraform Apply
        if: github.event_name == 'push'
        run: |
          cd deployment  
          terraform apply -auto-approve
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
