version: "3.8"

services:
  web:
    build:
      context: ..
      dockerfile: local-test/Dockerfile
    container_name: animus_app
    expose:
      - "8000"
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 -m 007 app:app

  nginx:
    image: nginx:latest
    container_name: animus_nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
