name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: maciejgrosz
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./deployment
          push: true
          tags: registry.digitalocean.com/animus-420/animus:latest

      - name: Sync deployment files to Droplet
        run: |
          rsync -avz --delete ./deployment/ /var/www/animus/
        env:
          RSYNC_RSH: "ssh -i ${{ secrets.DROPLET_SSH_KEY }} -o StrictHostKeyChecking=no"

      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/animus
            # Pull the updated images
            docker-compose pull
            # Recreate and start the containers in detached mode
            docker-compose up -d
            # Optionally, remove unused images
            docker image prune -f
