name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: maciejgrosz
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./deployment
          dockerfile: Dockerfile
          push: true
          tags: registry.digitalocean.com/animus-420/animus:latest
      - name: Set up SSH key file for rsync
        run: |
          echo "${{ secrets.DROPLET_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Sync deployment files to Droplet using rsync with sudo
        run: |
          rsync -avz --delete ./deployment/ ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}:/var/www/animus/
        env:
          RSYNC_RSH: "ssh -i key.pem -o StrictHostKeyChecking=no"
          RSYNC_PATH: "sudo rsync"

      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: 22
          script: |
            # Log in to the DigitalOcean Container Registry
            docker login registry.digitalocean.com -u maciejgrosz -p ${{ secrets.REGISTRY_TOKEN }}
            cd /var/www/animus
            docker-compose pull
            docker-compose up -d
            docker image prune -f

